logging:
  level:
    ROOT: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
