spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    driver-class-name: oracle.jdbc.OracleDriver
#    type: oracle.ucp.jdbc.PoolDataSource
    type: org.apache.tomcat.jdbc.pool.DataSource
    username: vshop
    password: vshop
    tomcat:
      validation-query: select * from dual
      default-auto-commit: false

  #    ucp:
#      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
#      s-q-l-for-validate-connection: select * from dual
#      connection-pool-name: oracle-connection-pool
#      initial-pool-size: 5
#      min-pool-size: 1
#      max-pool-size: 30
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.Oracle12cDialect
        show_sql: false
        cache:
          query_cache_factory: true
        connection:
          autocommit: false
springdoc:
  show-actuator: true
  swagger-ui:
    path: /
logging:
  level:
    org.springframework.jdbc: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
vshop:
  products:
    generate:
      initial:
        size: 1000000