logging:
  level:
    ROOT: INFO
    pl.malirz.vshop: DEBUG
    org.springframework.jdbc: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.data.mongodb: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO
  charset:
    console: UTF-8
