spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    driver-class-name: oracle.jdbc.OracleDriver
    username: vshop
    password: vshop
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      validation-query: select * from dual
      default-auto-commit: false
  # If you prefer UCP
  #    type: oracle.ucp.jdbc.PoolDataSource
  #    ucp:
  #      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
  #      s-q-l-for-validate-connection: select * from dual
  #      connection-pool-name: oracle-connection-pool
  #      initial-pool-size: 5
  #      min-pool-size: 1
  #      max-pool-size: 30
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
        dialect: org.hibernate.dialect.Oracle12cDialect
        show_sql: false
        cache:
          query_cache_factory: true
        connection:
          autocommit: false