springdoc:
  show-actuator: true
  swagger-ui:
    path: /
logging:
  level:
    ROOT: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
vshop:
  products:
    generate:
      initial:
        size: 10